---
linters-settings:
  godot:
    exclude: '^ @' # swag comments
  tagliatelle:
    case:
      use-field-name: false
      rules:
        json: snake

linters:
  enable-all: true
  disable:
    - cyclop
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gofumpt
    - golint
    - gomnd
    - ifshort
    - interfacer
    - ireturn
    - maligned
    - musttag
    - nlreturn
    - nosnakecase
    - rowserrcheck
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - testableexamples
    - varcheck
    - varnamelen
    - wastedassign
    - wrapcheck

    # FIXME (alkurbatov): Enable when we add parallelism to the tests.
    - paralleltest

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - noctx
