// Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Alexander Kurbatov",
            "email": "sir.alkurbatov@yandex.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get HTML page with full list of stored metrics",
                "operationId": "metrics_list",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "tags": [
                    "Healthcheck"
                ],
                "summary": "Verify connection to the database",
                "operationId": "health_info",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Connection is broken",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "501": {
                        "description": "Server is not configured to use database",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Push metric data as JSON",
                "operationId": "metrics_json_update",
                "parameters": [
                    {
                        "description": "Request parameters.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/metrics.MetricReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/metrics.MetricReq"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "501": {
                        "description": "Metric type is not supported",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/update/{type}/{name}/{value}": {
            "post": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Push metric data.",
                "operationId": "metrics_update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metrics type (e.g. ` + "`" + `counter` + "`" + `, ` + "`" + `gauge` + "`" + `).",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Metrics name.",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Metrics value, must be convertable to ` + "`" + `int64` + "`" + ` or ` + "`" + `float64` + "`" + `.",
                        "name": "value",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "501": {
                        "description": "Metric type is not supported",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/updates": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Push list of metrics data as JSON",
                "operationId": "metrics_json_update_list",
                "parameters": [
                    {
                        "description": "List of metrics to update.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/metrics.MetricReq"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/metrics.MetricReq"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "501": {
                        "description": "Metric type is not supported",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/value": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get metrics value as JSON",
                "operationId": "metrics_json_info",
                "parameters": [
                    {
                        "description": "Request parameters: ` + "`" + `id` + "`" + ` and ` + "`" + `type` + "`" + ` are required.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/metrics.MetricReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/metrics.MetricReq"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Metric not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "501": {
                        "description": "Metric type is not supported",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/value/{type}/{name}": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get metrics value as string",
                "operationId": "metrics_info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metrics type (e.g. ` + "`" + `counter` + "`" + `, ` + "`" + `gauge` + "`" + `).",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Metrics name.",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Metric not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "501": {
                        "description": "Metric type is not supported",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "metrics.MetricReq": {
            "type": "object",
            "properties": {
                "delta": {
                    "description": "Metric value if type is counter, must not be set for other types.",
                    "type": "integer"
                },
                "hash": {
                    "description": "Hash value of the data, may be omitted if signature validation is\ndisabled on server-side.",
                    "type": "string"
                },
                "id": {
                    "description": "Name of a metric.",
                    "type": "string"
                },
                "type": {
                    "description": "One of supported metric kinds (e.g. counter, gauge), see constants.",
                    "type": "string"
                },
                "value": {
                    "description": "Metric value if type is gauge, must not be set for other types.",
                    "type": "number"
                }
            }
        }
    },
    "tags": [
        {
            "description": "\"Metrics API\"",
            "name": "Metrics"
        },
        {
            "description": "\"API to inspect service health state\"",
            "name": "Healthcheck"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Metrics collector API",
	Description:      "Service for storing metrics data.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
